# Generated by Django 5.0.6 on 2026-04-23 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                ('amount', models.IntegerField(help_text='Amount in UZS tiyin')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('click', 'Click'), ('payme', 'Payme'), ('card', 'Card')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='organizations.organization')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-paid_at'],
            },
        ),
    ]
